# -*- coding: utf-8 -*-
# Source data for typing texts. Quotes are public domain (authors died > 70 years ago, or traditional proverbs).
SENT = {
"general": [
"The morning sun rose slowly over the quiet town while the baker opened his little shop.",
"She packed a small bag, locked the door, and walked to the station without looking back.",
"A gentle breeze moved through the orchard and shook the last apples from the old trees.",
"Every evening the children gathered by the river to watch the boats drift toward the sea.",
"He found an old map in the attic, and suddenly the whole summer felt like an adventure.",
"The market was full of colors, voices, and the warm smell of fresh bread and mint tea.",
"After the rain, the streets shone like mirrors and the air smelled of earth and flowers.",
"My grandmother tells the best stories, and she always ends them with a clever question.",
"The train arrived exactly on time, which surprised everyone who had been waiting on the platform.",
"We climbed the hill before sunrise to see the valley wake up under a blanket of soft fog.",
"A small lamp glowed in the window, and the whole street seemed a little less lonely.",
"They painted the fence bright blue, and the neighbors smiled every time they walked by.",
"The library was silent except for the sound of turning pages and a distant clock.",
"On Sunday we cook together, laugh too loudly, and forget about the week that just passed.",
"The cat watched the rain from the windowsill as if it were a very boring television show.",
"He carried the heavy box up three flights of stairs and then realized it was empty.",
"Stars appeared one by one, and the desert became a huge quiet room with a glowing ceiling.",
"Please remember that a good habit is built slowly, one ordinary day after another.",
"The old fisherman mended his net and hummed a song that nobody else remembered.",
"Our teacher said that curiosity is a muscle, and the more we use it, the stronger it grows.",
"Two friends shared one umbrella and somehow both of them still got completely wet.",
"The festival began at dusk with music, lanterns, and a long table full of generous food.",
"Somewhere in the city a street musician played a melody that made strangers slow down.",
"Breakfast was simple: warm bread, olive oil, honey, and a glass of sweet orange juice.",
"When the power went out, we lit candles and told stories until the house felt like a castle.",
"The bridge connects two parts of the city, and every morning thousands of people cross it.",
"A quick brown fox jumps over the lazy dog near the bank of the river.",
"Pack my box with five dozen liquor jugs, then send them quickly across the bay.",
"The explorer wrote in her journal every night, even when her hands were cold and tired.",
"Slowly the ferry left the harbor, and the white city turned into a line of tiny lights."],
"tech": [
"A computer program is a list of instructions that a machine follows with perfect obedience.",
"Good software is written for humans to read, and only incidentally for computers to run.",
"The network was slow because one small cable had been loose for three long months.",
"Before you optimize the code, measure it, because the slow part is rarely where you expect.",
"Artificial intelligence learns patterns from data, but people still decide what matters.",
"A strong password is long, unique, and stored safely in a trusted password manager.",
"The team released a new version every Friday and fixed the bugs before the weekend.",
"Cloud servers let small teams build big products without owning a single physical machine.",
"Every pixel on the screen is just a tiny light that obeys a number stored in memory.",
"When the application crashed, the logs told a clear story about a missing configuration file.",
"An algorithm is a recipe: a clear list of steps that turns input into a useful result.",
"Keep your phone updated, because many security problems are fixed in the newest version.",
"The developer drank coffee, stared at the error message, and finally found the missing comma.",
"Encryption scrambles information so that only the person with the right key can read it.",
"Modern phones contain more computing power than the machines that sent people to the moon.",
"A database stores information in tables, and a query asks it a precise question.",
"Testing your code feels slow at first, but it saves you from painful surprises later.",
"The robot followed the line on the floor and stopped exactly where the light turned red.",
"Open source means that anyone can read, improve, and share the code that powers a project.",
"Fast typing is a superpower for programmers because ideas move at the speed of the keyboard.",
"A backup that you never tested is only a hopeful story about your important files.",
"Wireless signals travel through the air as invisible waves carrying music, video, and messages.",
"Battery life improves when screens are dimmed, apps are closed, and updates are scheduled wisely.",
"Version control remembers every change, so you can travel back in time when something breaks.",
"The search engine read millions of pages and returned the answer in less than a second."],
"football": [
"The striker controlled the ball with his chest and fired a shot into the top corner.",
"Fans sang together for ninety minutes, and the whole stadium shook with every goal.",
"A perfect pass split the defense, and the winger raced toward the goal with open space ahead.",
"The goalkeeper dived to his left and pushed the penalty onto the post with his fingertips.",
"Our captain never stops running, talking, and encouraging everyone until the final whistle.",
"The referee checked the video screen and decided that the goal was clean and fair.",
"She scored twice in the second half and lifted the trophy in front of a roaring crowd.",
"The coach changed the formation at halftime, and suddenly the midfield controlled the game.",
"A late corner kick found the tall defender, and his header won the match in stoppage time.",
"Young players train every day on dusty fields and dream of playing in the biggest stadiums.",
"The crowd held its breath while the midfielder placed the ball carefully for the free kick.",
"Teamwork wins tournaments: one great player can shine, but a united team becomes unstoppable.",
"The ball curved around the wall, kissed the crossbar, and dropped gently into the net.",
"After ninety tense minutes and thirty more in extra time, the match went to penalties.",
"He practiced free kicks every evening until the sun went down and the lights came on.",
"The home team pressed high, won the ball back, and scored within ten seconds.",
"A clean tackle at the right moment can feel as exciting as a goal for true defenders.",
"The whole neighborhood gathered around one small television to watch the final together.",
"Their defense was a wall, their midfield an engine, and their attack pure lightning.",
"With a quick turn and a sharp step, the dribbler left three defenders behind him.",
"The league table changes every week, and one lucky goal can rewrite the whole story.",
"Nobody in the stadium left early, because this team had already won late games before.",
"The new stadium has a grass pitch, bright lights, and seats close enough to hear every shout.",
"Every great comeback starts with one small goal and a crowd that refuses to go quiet.",
"She wore number ten, played with her head up, and saw passes that nobody else could see."],
"games": [
"The hero collected three golden keys and opened the secret door at the end of the dungeon.",
"In this level you must jump carefully, because the floating platforms disappear after one second.",
"The final boss has three health bars, a giant sword, and a very dramatic entrance.",
"Save your game before entering the castle, because nobody survives the first room without a plan.",
"A perfect combo fills the power meter, and the whole screen explodes with color and sound.",
"The racing game lets you upgrade your engine, change your paint, and add glowing wheels.",
"He unlocked the legendary car after winning twenty races without a single mistake.",
"Coins spin in the air, music gets faster, and the timer reminds you that every second counts.",
"The puzzle looked impossible until she noticed that the shadows pointed to the hidden switch.",
"Good game design teaches the player without a single long tutorial or a boring lecture.",
"Players gather in the virtual city to trade items, explore caves, and build tall towers.",
"The speedrunner knew every corner, every shortcut, and every pixel of the map by heart.",
"Press the button at the right moment and your character will leap over the glowing lava.",
"A quiet forest level with soft music can be as exciting as a fast chase through a city.",
"The dragon sleeps on a mountain of gold, and only a careful hero can sneak past it.",
"Level up your skills, choose your gear, and prepare for the tournament at the end of the season.",
"The map shows five islands, three secret caves, and one mysterious lighthouse in the fog.",
"Her score climbed higher with every clean stroke, and soon the leaderboard had a new leader.",
"When the lights turned green, every engine roared and the crowd leaned forward together.",
"A rare skin appeared in the shop for just one weekend, and everyone rushed to get it.",
"The arcade smelled like popcorn, and every machine blinked with bright invitations to play.",
"He practiced the same jump for an hour until it finally became smooth and automatic.",
"In cooperative mode, one player guards the gate while the other solves the ancient riddle.",
"Victory feels sweeter when you lose five times first and learn something new from each defeat.",
"The pixel art was simple, but every tiny animation was full of humor and heart."],
"sports": [
"The marathon runner kept a steady rhythm, breathing slowly and focusing on the next kilometer.",
"In tennis, the match can change in a single point, so you must stay calm and keep moving.",
"The swimmer pushed off the wall, glided under the water, and exploded into a powerful stroke.",
"A strong team of cyclists rides in a line, sharing the wind and saving energy for the final sprint.",
"She trained before school and after school, and the gold medal was earned in the quiet hours.",
"The basketball bounced twice, rolled around the rim, and finally dropped through the net.",
"Stretching before exercise protects your muscles and prepares your body for hard work.",
"The sprinter crouched at the line, listened for the signal, and flew down the track.",
"Sleep, water, and healthy food are as important to an athlete as hours of training.",
"The mountain climbers started at midnight so they could reach the summit before the morning storm.",
"A good coach sees potential before the athlete does and patiently helps it grow.",
"On the last lap, the crowd stood up and cheered every single runner across the finish line.",
"The volleyball soared over the net, and the defender dived full length to save it.",
"Boxers move lightly on their feet, keep their hands high, and watch their opponent's shoulders.",
"Throwing a javelin needs speed, balance, and the perfect angle at the exact right moment.",
"Gymnasts make difficult moves look easy only after thousands of patient repetitions.",
"The rowing team moved as one, and the boat slid across the lake like a silver needle.",
"Winning is great, but finishing a hard race you once thought impossible is even better.",
"A skateboard, a flat street, and a few friends are all you need for a wonderful afternoon.",
"The referee raised the flag, the timer stopped, and the whole arena exhaled at once."],
"motivation": [
"Small steps every day will take you farther than a giant leap you never actually take.",
"You do not need to be perfect; you only need to be a little better than yesterday.",
"Mistakes are proof that you are trying, and every expert was once a confused beginner.",
"Start where you are, use what you have, and do what you can, then repeat tomorrow.",
"Confidence grows from practice, and practice begins with the courage to do it badly first.",
"The road is long, but the view from the top belongs to those who keep walking.",
"Stay patient with yourself, because real progress is quiet and slow and absolutely worth it.",
"Do not compare your first chapter with someone else's final chapter.",
"When you feel like stopping, remember why you started and take one more step.",
"Discipline is choosing what you want most over what you want right now.",
"Every champion was once a beginner who refused to give up on the hard days.",
"Your only competition is the person you were yesterday, so race against that one.",
"Focus on the next word, then the next, and soon you will reach the finish line.",
"Hard work beats talent when talent does not work hard, and you can work hard today.",
"Breathe, reset, and try again; a calm mind is faster than an angry one.",
"Dream big, plan small, and act today, because tomorrow is made of what you do now.",
"A strong mind is trained like a strong body: with patience, repetition, and rest.",
"Fall seven times, stand up eight, and learn something useful on every fall.",
"Be kind to yourself when you fail and strict with yourself when you make excuses.",
"The best time to begin was yesterday; the second best time is right now.",
"Progress is not a straight line, but it always moves forward for those who stay.",
"You are stronger than your doubts and faster than your fears, so keep on typing.",
"Success is the sum of small efforts repeated day in and day out with love.",
"Turn your obstacles into stepping stones and your lessons into wings.",
"If it is important to you, you will find a way; if not, you will find an excuse."],
}
QUOTES = [
("All that glisters is not gold.","William Shakespeare"),
("To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man.","William Shakespeare"),
("The fault, dear Brutus, is not in our stars, but in ourselves, that we are underlings.","William Shakespeare"),
("Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.","William Shakespeare"),
("Brevity is the soul of wit.","William Shakespeare"),
("Better three hours too soon than a minute too late.","William Shakespeare"),
("If music be the food of love, play on.","William Shakespeare"),
("Love all, trust a few, do wrong to none.","William Shakespeare"),
("We are such stuff as dreams are made on, and our little life is rounded with a sleep.","William Shakespeare"),
("Though this be madness, yet there is method in it.","William Shakespeare"),
("Government of the people, by the people, for the people, shall not perish from the earth.","Abraham Lincoln"),
("Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty.","Abraham Lincoln"),
("Early to bed and early to rise makes a man healthy, wealthy, and wise.","Benjamin Franklin"),
("Well done is better than well said.","Benjamin Franklin"),
("Lost time is never found again.","Benjamin Franklin"),
("A penny saved is a penny earned.","Benjamin Franklin"),
("Energy and persistence conquer all things.","Benjamin Franklin"),
("Nothing great was ever achieved without enthusiasm.","Ralph Waldo Emerson"),
("The only way to have a friend is to be one.","Ralph Waldo Emerson"),
("Trust thyself: every heart vibrates to that iron string.","Ralph Waldo Emerson"),
("If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.","Henry David Thoreau"),
("It is not enough to be busy; so are the ants. The question is, what are we busy about?","Henry David Thoreau"),
("Courage is resistance to fear, mastery of fear, not absence of fear.","Mark Twain"),
("Always do right. This will gratify some people and astonish the rest.","Mark Twain"),
("Kindness is the language which the deaf can hear and the blind can see.","Mark Twain"),
("We are all in the gutter, but some of us are looking at the stars.","Oscar Wilde"),
("Experience is simply the name we give our mistakes.","Oscar Wilde"),
("Slow and steady wins the race.","Aesop"),
("United we stand, divided we fall.","Aesop"),
("No act of kindness, no matter how small, is ever wasted.","Aesop"),
("It is easy to be brave from a safe distance.","Aesop"),
("Look before you leap.","Aesop"),
("Honesty is the first chapter in the book of wisdom.","Thomas Jefferson"),
("It is hard to fail, but it is worse never to have tried to succeed.","Theodore Roosevelt"),
("Do what you can, with what you have, where you are.","Theodore Roosevelt"),
("Curiouser and curiouser!","Lewis Carroll"),
("Why, sometimes I have believed as many as six impossible things before breakfast.","Lewis Carroll"),
("It is no use going back to yesterday, because I was a different person then.","Lewis Carroll"),
("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.","Charles Dickens"),
("No one is useless in this world who lightens the burden of it for anyone else.","Charles Dickens"),
("There is no charm equal to tenderness of heart.","Jane Austen"),
("If there is no struggle, there is no progress.","Frederick Douglass"),
("The secret of success is constancy to purpose.","Benjamin Disraeli"),
("Genius is one percent inspiration and ninety-nine percent perspiration.","Thomas Edison"),
("To strive, to seek, to find, and not to yield.","Alfred Tennyson"),
("It is better to have loved and lost than never to have loved at all.","Alfred Tennyson"),
("The world is so full of a number of things, I am sure we should all be as happy as kings.","Robert Louis Stevenson"),
("If you can keep your head when all about you are losing theirs, you will be a man, my son.","Rudyard Kipling"),
("All warfare is based on deception.","Sun Tzu"),
("Supreme excellence consists in breaking the enemy's resistance without fighting.","Sun Tzu"),
("If you know the enemy and know yourself, you need not fear the result of a hundred battles.","Sun Tzu"),
("Well begun is half done.","Proverb"),
("A journey of a thousand miles begins with a single step.","Proverb"),
("Practice makes perfect.","Proverb"),
("Actions speak louder than words.","Proverb"),
("Fortune favors the bold.","Proverb"),
("Where there is a will, there is a way.","Proverb"),
("The best way of avenging thyself is not to become like the wrong doer.","Marcus Aurelius"),
("A rolling stone gathers no moss.","Proverb"),
("The early bird catches the worm.","Proverb"),
("Rome was not built in a day.","Proverb"),
]
STORIES = [
"Mina found a tiny robot in the garden, covered in mud and blinking a weak green light. She carried it home, cleaned it with a soft cloth, and gave it a cup of warm water for its battery. By morning it was humming and rolling around the kitchen, and from that day on it followed her everywhere.",
"The lighthouse keeper had never seen a ship in the storm until that night. A small boat fought the waves, and he climbed the stairs two at a time to turn the big lamp. The beam swept across the water, and the boat slowly found its way to the harbor.",
"Omar opened the old wooden chest and found a compass that pointed in a strange direction. Curious, he followed it past the market, across the bridge, and into a quiet park. Under a large tree he discovered a small box with a note that said: well done, explorer.",
"In a village at the edge of the desert, a little girl planted one seed every morning. People laughed and said the sand was too dry. Years later, a green garden stood there, and travelers stopped to rest in the shade of her patient work.",
"The racer stood at the starting line with his hands shaking a little. He took a deep breath, whispered a short promise to himself, and pressed the pedal when the lights changed. The road became a silver river, and for the first time he felt completely free.",
"A fox and a crow met under a tall tree. The crow held a piece of bread in her beak, and the fox praised her voice until she opened her mouth to sing. The bread fell, the fox ran away, and the crow learned that flattery is rarely free.",
"Every night the old clock in the square struck thirteen instead of twelve. Nobody knew why, and nobody dared to fix it. One winter the clockmaker finally climbed up and found a small bird living inside, keeping its nest warm among the gears.",
"Lina wanted to learn the violin, but her first notes sounded like a cat in a storm. She practiced every day for a month, then for a year. At the school concert, the room fell silent, and her song floated out like a bright ribbon.",
"The astronaut looked through the small window at the blue planet far below. Everything she loved was in that tiny circle, and all the borders were invisible from here. She smiled, checked her instruments, and whispered thank you to everyone on Earth.",
"Yassine opened his shop early every day, even when no customers came. He cleaned the shelves, arranged the fruit, and greeted the street like a friend. After a year the street greeted him back, and his little shop became the heart of the neighborhood.",
"A traveler reached a river with no bridge and sat down to think. A heron stood nearby, patient and silent. The traveler watched how it walked only on the stones, and soon he crossed safely, stepping carefully from one stone to the next.",
"The mountain village received snow only once every ten years, and the children had never seen it. When the first flakes fell, they ran outside with open hands, laughing and catching the cold stars until their cheeks turned red.",
"The baker woke at three in the morning, long before the birds. He mixed the dough, lit the oven, and shaped the loaves by hand. When the sun came up, the whole street smelled like warm bread and welcome.",
"Nora built a kite from old paper and thin sticks. The first three flights ended in the bushes, but the fourth caught the wind and climbed high above the roofs. She held the string tightly and felt like she was touching the clouds.",
"A little submarine explored the dark sea, where strange fish glowed like lanterns. Its captain, a young scientist, wrote down every discovery. On the last day, a giant whale passed slowly by, and the ocean seemed to say hello.",
]
CODE = [
"for (int i = 0; i < 10; i++) { print(i); }",
"if (score >= 100 && lives > 0) { levelUp(); }",
"const sum = (a, b) => a + b;",
"def greet(name): return 'Hello, ' + name",
"final list = [1, 2, 3].map((e) => e * 2).toList();",
"while (running) { update(dt); render(); }",
"SELECT name, score FROM players WHERE score > 500 ORDER BY score DESC;",
"void main() { runApp(const MyApp()); }",
"let speed = Math.max(0, base - penalty);",
"class Car extends Vehicle { int gear = 1; }",
"import 'package:flutter/material.dart';",
"git commit -m \"Add nitro effect\" && git push origin main",
"function isEven(n) { return n % 2 === 0; }",
"var total = items.reduce((a, b) => a + b.price, 0);",
"try { await save(); } catch (e) { log(e); }",
"<div class=\"car\"><span>Turbo</span></div>",
"for x in range(5): print(x * x)",
"public static void main(String[] args) { }",
"npm install && npm run build",
"if (!list.isEmpty) return list.first;",
"const user = { name: 'Sara', level: 12 };",
"int fib(int n) => n < 2 ? n : fib(n - 1) + fib(n - 2);",
"await Future.delayed(Duration(seconds: 2));",
"result = [x for x in data if x % 2 == 0]",
"docker run -p 8080:80 --name web nginx",
"switch (state) { case 0: start(); break; default: stop(); }",
"String label = isWinner ? 'Winner' : 'Try again';",
"#include <stdio.h> int main() { return 0; }",
"body { margin: 0; background: #101020; color: #fff; }",
"Future<void> load() async { data = await fetch(url); }",
"map.forEach((key, value) => print('$key: $value'));",
"arr.sort((a, b) => b.score - a.score);",
"if (x == null) { throw Exception('missing value'); }",
"let wpm = (chars / 5) / minutes;",
"enum Gear { first, second, third, fourth }",
"SELECT COUNT(*) FROM races WHERE won = 1;",
"pip install flame riverpod",
"final accuracy = correct / total * 100;",
"echo \"Race finished\" >> log.txt",
"@override Widget build(BuildContext context) { return Container(); }",
"const items = await db.collection('users').get();",
]
WORDS_SHORT = "go run fast car bike road race win gear nitro turn left right speed drive start stop lap lane flag fuel tire wheel skid drift boost jump dash zoom spin rush blaze storm wind rain snow sand city neon star moon sun sky sea wave hill rock tree leaf wolf fox bird fish lion bear hawk king queen hero team goal play game level coin gem gold silver bronze power skill focus calm swift quick sharp clean clear bold brave keen wise warm cool bright dark light heavy small tiny big huge long short high low near far open close first last next back home work rest walk talk type key code data byte bit chip map path leap step hand foot head mind soul heart love hope dream trust faith peace joy fun".split()
WORDS_LONG = "adventure champion challenge development dangerous excellent experience extraordinary fantastic generation incredible information journey keyboard landscape magnificent motorcycle navigation opportunity performance powerful practice precision progress quickly remarkable responsible reliable strategy successful technology tournament transformation unbelievable victory wonderful accelerate acceleration achievement atmosphere brilliant competition concentration confidence determination discipline enthusiasm exhilarating formidable horizon imagination legendary momentum overtaking persistence spectacular thunderous unstoppable velocity accuracy".split()
PUNCT_TEMPLATES = [
"Wait, what? No way! It costs $%d.%02d, right?",
"Dear friend, on %d/%d/2026 we'll meet at %d:%02d p.m.; don't be late!",
"Order #%d: %d items, total $%d.%02d (tax included).",
"\"Ready?\" she asked. \"Yes,\" he said, \"let's go; we have %d minutes.\"",
"Room %d, floor %d: call 555-%04d before %d:%02d a.m., please.",
"Score: %d-%d! That's +%d%% better than last week, isn't it?",
"Tickets (%d adults, %d children) cost $%d; bring your ID, okay?",
"In %d days, we'll travel %d km; that's %d.%d hours by train!",
"Is it %d + %d = %d? Yes; and %d - %d = %d, too.",
"Coordinates: %d.%d N, %d.%d E; altitude %d m; temperature %d C.",
]
SYMBOL_TEMPLATES = [
"user_%d@mail.com | pass: P@ss#%d! | ref=%d&id=%d",
"if (a[%d] >= b[%d] && c != %d) { x += %d * 2; }",
"https://game.example/race?id=%d&lvl=%d#top",
"C:\\\\Games\\\\Racer\\\\save_%d.dat -> 100%% (%d/%d)",
"{ \"speed\": %d, \"nitro\": [%d, %d], \"ok\": true }",
"#%06x ~ rgb(%d, %d, %d) * 50%% + $%d",
"$total = ($a + $b) * %d / %d; // ~%d%%",
"<tag id=\"n%d\" value='%d'> & </tag> @%d",
]
FR_SENT = [
"Le soleil se lève doucement sur la ville et les rues commencent à se remplir de vie.",
"Chaque matin, le boulanger ouvre sa boutique et l'odeur du pain chaud traverse tout le quartier.",
"Nous avons marché longtemps au bord de la mer, en parlant de nos rêves et de nos projets.",
"La bibliothèque est un endroit calme où chaque livre attend patiemment son prochain lecteur.",
"Il faut toujours garder espoir, même quand le chemin semble long et difficile.",
"Les enfants jouent dans le jardin pendant que leurs parents préparent un grand repas.",
"Le train est arrivé à l'heure, et tous les voyageurs sont montés dans les wagons en souriant.",
"Mon ami m'a offert un vieux livre qui raconte l'histoire d'un voyage autour du monde.",
"La pluie tombe doucement sur les toits et le vent joue avec les feuilles des arbres.",
"Apprendre à taper vite demande de la patience, de la concentration et un peu de pratique chaque jour.",
"Le champion s'est entraîné pendant des mois pour réaliser enfin le rêve de toute sa vie.",
"Dans ce petit village, tout le monde se connaît et chacun salue ses voisins avec un sourire.",
"La voiture rouge a traversé le désert à toute vitesse sous un ciel immense et bleu.",
"Au marché, les couleurs des fruits et des légumes racontent déjà la fin de l'été.",
"Elle a ouvert la fenêtre, respiré l'air frais du matin et commencé une nouvelle journée.",
"Les étoiles brillent dans la nuit comme des lanternes accrochées au plafond du monde.",
"Un bon pilote garde son calme, regarde loin devant lui et reste toujours concentré.",
"Nous préparons une surprise pour l'anniversaire de notre grand-mère, mais chut, c'est un secret.",
"La montagne était couverte de neige, et le silence donnait à la vallée un air de conte.",
"Le jeune musicien a joué sa mélodie préférée et toute la salle est restée silencieuse.",
"Après la course, les pilotes se sont serré la main et ont souri pour les photographes.",
"Le chat dort sur le canapé pendant que la radio joue une chanson douce dans la cuisine.",
"Les vacances approchent, et toute la famille rêve de plage, de soleil et de glaces.",
"Le professeur explique que chaque erreur est une occasion d'apprendre quelque chose de nouveau.",
"Sur la place du village, les habitants dansent et chantent jusqu'à tard dans la nuit.",
"Un petit bateau quitte le port au lever du jour et disparaît lentement dans la brume.",
"La technologie change notre vie, mais elle ne remplace jamais un bon sourire.",
"Le football rassemble les amis, les familles et même les inconnus autour d'une même passion.",
"Il a appuyé sur l'accélérateur, et la moto a bondi comme un cheval libre sur la route.",
"Les voyages nous apprennent que le monde est grand, mais que les gens se ressemblent.",
]
FR_QUOTES = [
("Il faut cultiver notre jardin.","Voltaire"),
("Rien n'est plus puissant qu'une idée dont l'heure est venue.","Victor Hugo"),
("Le doute n'est pas une condition agréable, mais la certitude est absurde.","Voltaire"),
("Toute la vie est un apprentissage.","Proverbe"),
("Petit à petit, l'oiseau fait son nid.","Proverbe"),
("Qui veut voyager loin ménage sa monture.","Jean Racine"),
("La patience est amère, mais son fruit est doux.","Jean-Jacques Rousseau"),
("Rien ne sert de courir; il faut partir à point.","Jean de La Fontaine"),
("Aide-toi, le ciel t'aidera.","Jean de La Fontaine"),
("L'appétit vient en mangeant.","François Rabelais"),
("Tout vient à point à qui sait attendre.","Proverbe"),
("La raison du plus fort est toujours la meilleure.","Jean de La Fontaine"),
("Je pense, donc je suis.","René Descartes"),
("Ce qui se conçoit bien s'énonce clairement.","Nicolas Boileau"),
("Patience et longueur de temps font plus que force ni que rage.","Jean de La Fontaine"),
("Mieux vaut tard que jamais.","Proverbe"),
("Le temps est un grand maître, dit-on; le malheur est qu'il tue ses élèves.","Hector Berlioz"),
("Il n'y a point de chemin vers le bonheur; le bonheur est le chemin.","Proverbe"),
]
ES_SENT = [
"El sol sale despacio sobre la ciudad y las calles comienzan a llenarse de vida.",
"Cada mañana el panadero abre su tienda y el olor a pan caliente recorre todo el barrio.",
"Aprender a escribir rápido requiere paciencia, concentración y un poco de práctica cada día.",
"Los niños juegan en el jardín mientras sus padres preparan una gran comida para todos.",
"El coche rojo cruzó el desierto a toda velocidad bajo un cielo enorme y azul.",
"La biblioteca es un lugar tranquilo donde cada libro espera a su próximo lector.",
"Nunca dejes de soñar, porque los sueños son el primer paso hacia cualquier meta.",
"El campeón entrenó durante meses para cumplir por fin el sueño de toda su vida.",
"En el mercado, los colores de las frutas anuncian que el verano está terminando.",
"Un buen piloto mantiene la calma, mira lejos y siempre está concentrado en el camino.",
"La lluvia cae suavemente sobre los tejados y el viento juega con las hojas de los árboles.",
"Viajar nos enseña que el mundo es grande, pero que las personas se parecen mucho.",
"El fútbol reúne a amigos, familias y desconocidos alrededor de una misma pasión.",
"Las estrellas brillan en la noche como faroles colgados del techo del mundo.",
"Más vale tarde que nunca, pero mejor todavía es empezar hoy mismo.",
"Poco a poco se va lejos, y cada día de práctica te acerca a tu mejor versión.",
"La moto aceleró de repente y el camino se convirtió en un río de luces.",
"Quien siembra paciencia cosecha velocidad, y la velocidad llega con la práctica.",
"El tren llegó puntual y todos los viajeros subieron a los vagones con una sonrisa.",
"Hoy vamos a competir contra nuestro mejor tiempo y a superar el récord de ayer.",
]
WORLD = {
"tangier":[
"Tangier sits where the Atlantic meets the Mediterranean, and from its white hills you can see Europe across the water.",
"The old medina of Tangier is a maze of blue doors, bright tiles, and cafes where friends share mint tea for hours.",
"Writers and artists have loved this city for a century, because every street seems to hold an unfinished story."],
"paris":[
"Paris lights up every evening, and the Eiffel Tower sparkles for five minutes at the top of each hour.",
"Along the river Seine, booksellers open green boxes full of old books, postcards, and forgotten maps.",
"A warm croissant, a small coffee, and a quiet street corner are all you need for a perfect Paris morning."],
"london":[
"London is a city of bridges, red buses, and clock towers, and its famous bell has marked the hours for generations.",
"In London parks, people read on green chairs while ducks and pigeons walk around as if they owned the place.",
"Underground trains rush beneath the streets, and millions of stories pass each other without a single word."],
"rome":[
"Rome was not built in a day, and every stone of the Colosseum remembers the roar of a crowd two thousand years ago.",
"Toss a coin into the Trevi Fountain, make a wish, and the legend says that you will return to the eternal city.",
"In Rome, the past is never far away: you can drink coffee beside a column that is older than most countries."],
"cairo":[
"Cairo sits beside the great river Nile, and on its edge the pyramids have watched the desert for forty five centuries.",
"In the old bazaar, copper lanterns shine, spices fill the air, and shopkeepers greet you like a long lost cousin.",
"The Nile carries boats with white sails past a city that never sleeps and always has time for one more story."],
"dubai":[
"Dubai rose from the desert with towers of glass, and the tallest of them touches the clouds above the sunny coast.",
"At sunset, the golden dunes outside the city turn red, and the silence is broken only by a soft desert wind.",
"Modern trains, floating gardens, and huge fountains show how quickly a bold dream can become a real place."],
"mumbai":[
"Mumbai never stops moving: trains full of commuters, colorful taxis, and sea breezes along the long curved bay.",
"Street vendors sell hot snacks, bright flowers, and sweet tea while the city hums with music from every corner.",
"The Gateway of India stands by the harbor, welcoming ships and travelers just as it has for a hundred years."],
"beijing":[
"Beijing is home to the Forbidden City, a palace with nearly one thousand buildings and red walls that glow at sunset.",
"The Great Wall winds over green mountains for thousands of kilometers, and every step on it feels like a step in history.",
"In quiet parks at dawn, people practice slow exercises while the old city wakes up with the smell of fresh tea."],
"tokyo":[
"Tokyo blends ancient temples and neon towers, and the crossing at Shibuya fills with thousands of people every minute.",
"Fast trains arrive to the second, vending machines glow on every corner, and politeness is part of the daily rhythm.",
"In spring, cherry blossoms cover the parks in soft pink, and families sit under the trees to share a quiet picnic."],
"sydney":[
"Sydney harbor sparkles under the sun, and the white sails of the Opera House look like shells resting on the water.",
"Surfers greet the waves at dawn, ferries cross the bay, and the famous bridge curves over the city like a steel rainbow.",
"Down under, summer arrives when winter begins elsewhere, and Christmas is celebrated on the beach."],
"rio":[
"Rio de Janeiro lives between green mountains and golden beaches, and a giant statue opens its arms above the city.",
"Samba drums echo through the streets, children play football on the sand, and the sunset paints the bay in orange.",
"The cable car climbs Sugarloaf Mountain, and from the top the whole shining coastline looks like a living postcard."],
"newyork":[
"New York is a city of yellow taxis, tall towers, and bright screens, and its green lady holds a torch for the world.",
"In Central Park, joggers, artists, and musicians share the same quiet paths in the middle of the busy metropolis.",
"Every street in Manhattan has a rhythm, and the subway hums beneath it like a giant heartbeat that never rests."],
}
OFFICIAL = [
"The ability to type quickly and accurately is a valuable skill in the modern world. Whether you are writing a message to a friend, preparing a report for school, or building software for millions of users, the keyboard is the bridge between your ideas and the screen. Fast typists do not look at their hands. They rely on memory, rhythm, and steady practice. Each day of careful effort makes the next day a little easier, and soon the fingers move almost by themselves.",
"A good racing driver studies the track before the race begins. He learns where the road turns, where the surface is smooth, and where he can safely go faster. In the same way, a good typist studies the text in front of her. She reads a few words ahead, keeps her eyes calm, and lets her fingers follow a steady beat. Speed comes from control, and control comes from patience. The fastest people are rarely the ones who rush, but the ones who stay relaxed.",
"Long ago, travelers crossed the great desert by following the stars. They walked at night when the air was cool and rested during the hot afternoon. Each traveler carried water, bread, and a small lamp, and each one knew that the journey could not be hurried. Step by step, the dunes changed color and the horizon moved closer. When they finally saw the green trees of the oasis, they understood that patience had been their best companion.",
"The city at night is full of quiet machines. Trains glide through tunnels beneath the streets, elevators carry sleepy workers to high offices, and traffic lights change from red to green for empty roads. Somewhere a baker starts the first oven of the day, and somewhere a student finishes one more page of homework. The world keeps moving, even when we are not watching, and every small task helps it turn a little further toward the morning.",
"Learning anything new follows the same pattern. At first it feels strange and slow, and every mistake seems large. Then one day you notice that a difficult task has become easy. Nobody announced the moment, and nobody gave you a prize, yet the change is real. This is how skills grow: quietly, through repetition, with small improvements that add up over weeks and months. Keep showing up, keep practicing, and let time do the rest of the work.",
"Modern vehicles use many sensors to understand the road around them. Cameras watch the lines, radar measures the distance to other cars, and tiny computers decide how much power each wheel needs. Even with all this technology, the most important part of any journey is still the attention of the driver. A calm mind, relaxed hands, and clear eyes are more valuable than any machine, because they help us make careful choices when the road surprises us.",
"Every morning the market comes alive before the sun is fully up. Farmers unload baskets of oranges, tomatoes, and fresh herbs, while shopkeepers arrange their tables with careful hands. The air fills with voices, laughter, and the smell of warm bread. By noon the streets are crowded and bright, and by evening the tables are empty again. Tomorrow the same happy work will begin once more, and nobody will ever grow tired of the beautiful noise.",
"Teamwork is the quiet engine behind every great achievement. A ship needs sailors, a concert needs musicians, and a race car needs mechanics who work through the night. Each person has a small job, yet every small job matters to the final result. When people trust one another and share a clear goal, ordinary effort becomes extraordinary. The finish line is only the last step of a long road that many people built together.",
]
